### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by TMNTturtleguy**
This is only for messaging purposes.

### CODE REVIEW

**Comment by TMNTturtleguy** [comment]
@pjft I am trying to see if this will reach you by e-mail since i am mentioning you here.  The files here are not up to date as it will take me some time to merge everything with the file limits.  I have a zipped file ready on mega for you to download.  i can share the link here if you get this in your e-mail.  Thanks

**Comment by pjft** [comment]
I do, thanks! I'm just taking today off from ES work, hopefully! :)


- Paulo Tavares

**Comment by TMNTturtleguy** [comment]
You deserve a day off!  No need to spend any time on this theme, but since you asked, here is a link to the most up to date version of the Theme.  It is currently optimized and running with the border.png file as the outline. The .svg file is still in the art folder as well, simply rename all files to border.svg to switch back and forth to see the differences.  I have added a lot of themes and modified a bit of code.  I now the 17 systems i have loaded are correct, there may be some tweaking left to do on the others!

Link: https://mega.nz/#!keIGHC7R!bOr_9Sj3L8CdeH0Bly8Q0WrZzudGPHVAiHrNcHPwLo0

Let me know when you have pulled it down and i will remove the file.  Thanks again for everything.

Kevin

**Comment by pjft** [comment]
Downloaded it! I'll let you know should I have any question, but glad to
hear that at least this is helping the theme out!

Thanks, and you have some time off as well :)

- Paulo Tavares

**Comment by TMNTturtleguy** [comment]
@pjft - no need to even look at this, but if you are interested I updated the theme on mega.  

https://mega.nz/#!IHJg1YZS!dTBpNDmWcca9lOUJ1dwBcDjxYIc4t7DjyPKJpqPWPE8

If you do try it out, let me know how the performance is.  To change back to the controllers:  Go to the theme.xml for system you want to change, modify logo2 to "true" and logo4 to "false".  Of course you can easily find/replace all so that it updates all the theme.xml to this setting.

**Pull request closed without merging**
